# Generated by Django 4.2.7 on 2026-08-15 05:15

import django.core.validators
from django.db import migrations, models
import mixins.mixing
import validation.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username can contain only letters, numbers and underscore', regex='^[a-zA-Z0-9_]+$')], verbose_name='username')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?\\d{10,15}$')], verbose_name='phone')),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='users/%Y/%m/%d/', validators=[validation.validators.validate_image_size, validation.validators.validate_file_extension], verbose_name='image')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='city')),
                ('home_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='home_city')),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='zip_code')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is_verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '01. User',
                'verbose_name_plural': '01. Users',
                'db_table': 'account_users',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['is_active', 'is_verified'], name='account_use_is_acti_9b834f_idx')],
            },
            bases=(mixins.mixing.StripMixin, mixins.mixing.ImageTagMixin, models.Model),
        ),
    ]
