# Generated by Django 4.2.7 on 2026-08-15 05:32

from django.db import migrations, models
import validation.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowpayment',
            name='image',
            field=models.ImageField(default='defaults/default.jpg', upload_to='allows_payments/%Y/%m/%d/', validators=[validation.validators.validate_image_size, validation.validators.validate_file_extension], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(default='defaults/default.jpg', upload_to='brands/%Y/%m/%d/', validators=[validation.validators.validate_image_size, validation.validators.validate_file_extension], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='defaults/default.jpg', upload_to='categories/%Y/%m/%d/', validators=[validation.validators.validate_image_size, validation.validators.validate_file_extension], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='defaults/default.jpg', upload_to='products/gallery/%Y/%m/%d/', validators=[validation.validators.validate_image_size, validation.validators.validate_file_extension], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(default='defaults/default.jpg', upload_to='sliders/%Y/%m/%d/', validators=[validation.validators.validate_image_size, validation.validators.validate_file_extension], verbose_name='image'),
        ),
    ]
