# Generated by Django 4.2.7 on 2026-08-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_allowpayment_image_alter_brand_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='slider',
            name='button',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='button'),
        ),
    ]
