# Generated by Django 4.2.7 on 2026-08-15 05:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cod', 'Cash on Delivery'), ('paypal', 'PayPal'), ('card', 'Card')], max_length=20, verbose_name='payment_method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('packed', 'Packed'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='is_finalized')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid_at')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='total_amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='discount_amount')),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='final_amount')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name_plural': '02. Checkout',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit_price')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name_plural': '03. Checkout Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_choice', models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], default='Home', max_length=20, verbose_name='shipping_choice')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('country', models.CharField(blank=True, max_length=150, null=True, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=150, null=True, verbose_name='city')),
                ('home_city', models.CharField(blank=True, max_length=150, null=True, verbose_name='home_city')),
                ('zip_code', models.CharField(blank=True, max_length=15, null=True, verbose_name='zip_code')),
                ('phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='phone')),
                ('address', models.TextField(blank=True, max_length=500, null=True, verbose_name='address')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '02. Shipping',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('90.00'))], verbose_name='discount_percent')),
                ('max_usage', models.PositiveIntegerField(default=1, verbose_name='max_usage')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='used_count')),
                ('max_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('1000.00'), max_digits=10, verbose_name='max_discount_amount')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='start_date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='end_date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
            options={
                'verbose_name_plural': '01. Coupon',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['code'], name='checkout_co_code_dc11db_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='coupon',
            constraint=models.CheckConstraint(check=models.Q(('discount_percent__lte', 90)), name='discount_percent_max_90'),
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.checkout'),
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='checkoutitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.variantoption'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='checkout.coupon'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.shipping'),
        ),
        migrations.AddField(
            model_name='checkout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='checkout',
            index=models.Index(fields=['user', 'status'], name='checkout_ch_user_id_d21923_idx'),
        ),
    ]
