# Generated by Django 4.2.7 on 2026-08-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkout',
            options={'ordering': ['id'], 'verbose_name_plural': '03. Checkout'},
        ),
        migrations.AlterModelOptions(
            name='checkoutitem',
            options={'ordering': ['id'], 'verbose_name_plural': '04. Checkout Items'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ['id'], 'verbose_name_plural': '02. Coupon'},
        ),
        migrations.AlterModelOptions(
            name='shipping',
            options={'ordering': ['id'], 'verbose_name_plural': '01. Shipping'},
        ),
        migrations.AlterField(
            model_name='shipping',
            name='address',
            field=models.TextField(default='Not provided', max_length=500, verbose_name='address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipping',
            name='city',
            field=models.CharField(default='Not provided', max_length=150, verbose_name='city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipping',
            name='country',
            field=models.CharField(default='Not provided', max_length=150, verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipping',
            name='home_city',
            field=models.CharField(default='Not provided', max_length=150, verbose_name='home_city'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipping',
            name='name',
            field=models.CharField(default='Not provided', max_length=150, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipping',
            name='phone',
            field=models.CharField(default='Not provided', max_length=16, verbose_name='phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipping',
            name='zip_code',
            field=models.CharField(default='Not provided', max_length=15, verbose_name='zip_code'),
            preserve_default=False,
        ),
    ]
