# Generated by Django 4.2.7 on 2026-08-15 05:15

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.variantoption')),
            ],
            options={
                'verbose_name_plural': '02. Wishlists',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['user'], name='cart_wishli_user_id_bbca57_idx'), models.Index(fields=['product'], name='cart_wishli_product_018042_idx'), models.Index(fields=['variant'], name='cart_wishli_variant_f85fbc_idx')],
                'unique_together': {('user', 'product', 'variant')},
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('stored_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='stored_unit_price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.variantoption')),
            ],
            options={
                'verbose_name_plural': '01. Carts',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['user'], name='cart_cart_user_id_b645f9_idx'), models.Index(fields=['product'], name='cart_cart_product_5a186d_idx'), models.Index(fields=['variant'], name='cart_cart_variant_5432e9_idx'), models.Index(fields=['paid'], name='cart_cart_paid_f5fcbf_idx')],
                'unique_together': {('user', 'product', 'variant', 'paid')},
            },
        ),
    ]
